apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: codefresh-cap-app-proxy
  namespace: codefresh
  annotations:
    cert-manager.io/cluster-issuer: ca-cluster-issuer-v2
    kubernetes.io/ingress.class: nginx-public
spec:
  rules:
  - host: cf.public.test.lifen.fr
    http:
      paths:
      - backend:
          service:
            name: cap-app-proxy
            port:
              number: 3017
        path: /app-proxy/
        pathType: Prefix
  tls:
  - hosts:
    - '*.public.test.lifen.fr'
    secretName: wildcard-public.test.lifen.fr-tls
status:
  loadBalancer: {}
